# Generated by Django 3.2 on 2021-05-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmany', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
